"""new functions and columns

Revision ID: 1486e8165535
Revises: 5af418948363
Create Date: 2020-06-22 15:48:49.991453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1486e8165535'
down_revision = '5af418948363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('goal', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_habit_goal'), 'habit', ['goal'], unique=False)
    op.add_column('system', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('system', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system', 'status')
    op.drop_column('system', 'date_created')
    op.drop_index(op.f('ix_habit_goal'), table_name='habit')
    op.drop_column('habit', 'goal')
    # ### end Alembic commands ###
