"""systems and habits table

Revision ID: 17aa29390778
Revises: 2410a8cadd12
Create Date: 2020-06-17 17:52:20.039323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17aa29390778'
down_revision = '2410a8cadd12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('descr', sa.String(length=120), nullable=True),
    sa.Column('creator', sa.String(length=90), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['user.email'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_system_descr'), 'system', ['descr'], unique=True)
    op.create_index(op.f('ix_system_title'), 'system', ['title'], unique=True)
    op.create_table('habit',
    sa.Column('hid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['system.sid'], ),
    sa.PrimaryKeyConstraint('hid')
    )
    op.create_index(op.f('ix_habit_goal'), 'habit', ['goal'], unique=False)
    op.create_index(op.f('ix_habit_progress'), 'habit', ['progress'], unique=False)
    op.create_index(op.f('ix_habit_title'), 'habit', ['title'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_index(op.f('ix_habit_title'), table_name='habit')
    op.drop_index(op.f('ix_habit_progress'), table_name='habit')
    op.drop_index(op.f('ix_habit_goal'), table_name='habit')
    op.drop_table('habit')
    op.drop_index(op.f('ix_system_title'), table_name='system')
    op.drop_index(op.f('ix_system_descr'), table_name='system')
    op.drop_table('system')
    # ### end Alembic commands ###
