"""habits table

Revision ID: 20c21f83e66a
Revises: 213bae299a28
Create Date: 2020-06-20 20:15:19.712317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c21f83e66a'
down_revision = '213bae299a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit',
    sa.Column('hid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['system.sid'], ),
    sa.PrimaryKeyConstraint('hid')
    )
    op.create_index(op.f('ix_habit_progress'), 'habit', ['progress'], unique=False)
    op.create_index(op.f('ix_habit_title'), 'habit', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habit_title'), table_name='habit')
    op.drop_index(op.f('ix_habit_progress'), table_name='habit')
    op.drop_table('habit')
    # ### end Alembic commands ###
