"""updated column

Revision ID: 213bae299a28
Revises: 95a333a7fb29
Create Date: 2020-06-18 18:04:07.813662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213bae299a28'
down_revision = '95a333a7fb29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('descr', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.String(length=90), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_system_descr'), 'system', ['descr'], unique=False)
    op.create_index(op.f('ix_system_title'), 'system', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_title'), table_name='system')
    op.drop_index(op.f('ix_system_descr'), table_name='system')
    op.drop_table('system')
    # ### end Alembic commands ###
