"""empty message

Revision ID: 5af418948363
Revises: 20c21f83e66a
Create Date: 2020-06-21 10:37:38.578704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af418948363'
down_revision = '20c21f83e66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system', 'user_id',
               existing_type=sa.VARCHAR(length=90),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system', 'user_id',
               existing_type=sa.VARCHAR(length=90),
               nullable=False)
    # ### end Alembic commands ###
