"""empty message

Revision ID: 75be409b89e8
Revises: 1486e8165535
Create Date: 2020-07-04 22:13:20.959506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75be409b89e8'
down_revision = '1486e8165535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_system_date_created'), 'system', ['date_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_date_created'), table_name='system')
    # ### end Alembic commands ###
