"""empty message

Revision ID: 8c2ba51bc475
Revises: 17aa29390778
Create Date: 2020-06-17 18:30:42.497957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2ba51bc475'
down_revision = '17aa29390778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
