"""systems table

Revision ID: 95a333a7fb29
Revises: 2410a8cadd12
Create Date: 2020-06-18 17:53:41.974958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a333a7fb29'
down_revision = '2410a8cadd12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('descr', sa.String(length=120), nullable=True),
    sa.Column('creator', sa.String(length=90), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['user.email'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_system_descr'), 'system', ['descr'], unique=False)
    op.create_index(op.f('ix_system_title'), 'system', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_title'), table_name='system')
    op.drop_index(op.f('ix_system_descr'), table_name='system')
    op.drop_table('system')
    # ### end Alembic commands ###
