"""empty message

Revision ID: e6d3b984c747
Revises: 8c2ba51bc475
Create Date: 2020-06-18 17:29:23.046455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d3b984c747'
down_revision = '8c2ba51bc475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
